# Generated by Django 4.1.1 on 2022-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_alter_claim_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='f_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='l_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
