# Generated by Django 4.1.1 on 2022-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_users_email_users_f_name_users_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
