# Generated by Django 4.1.1 on 2022-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_alter_claim_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
