# Generated by Django 4.1.1 on 2022-10-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_claim_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='file',
            new_name='pdf',
        ),
    ]
