# Generated by Django 4.1.1 on 2022-10-06 18:03

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_claim_price_currency_alter_claim_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='CZK', max_digits=14),
        ),
    ]
