# Generated by Django 4.1.1 on 2022-10-06 19:06

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0017_alter_claim_min_price_tranche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='min_price_tranche',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, default_currency='CZK', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='min_price_tranche_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='price_tranche',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, default_currency='CZK', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='price_tranche_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='remaining_ammount',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, default_currency='CZK', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='remaining_ammount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default='CZK', editable=False, max_length=3, null=True),
        ),
    ]
