# Generated by Django 4.1.1 on 2022-10-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_alter_claim_min_price_tranche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='min_price_tranche',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='min_price_tranche_currency',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='price_tranche',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='price_tranche_currency',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='remaining_ammount',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='remaining_ammount_currency',
        ),
    ]
