# Generated by Django 4.1.1 on 2022-10-06 19:16

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0021_claim_min_price_tranche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='remaining_ammount',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='remaining_ammount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna')], default=None, editable=False, max_length=3, null=True),
        ),
    ]
