# Generated by Django 4.1.1 on 2022-10-06 19:27

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0022_claim_remaining_ammount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='min_price_tranche',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, help_text='Enter a minimum price purchase', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='price_tranche',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('CZK', 'Czech Koruna')], decimal_places=0, help_text='Enter available amount', max_digits=14, null=True),
        ),
    ]
