# Generated by Django 4.1.5 on 2023-01-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
